### ISSUE TITLE
Facet for Fields of Science and co-author does not return to previous state after unchecking a item

### ISSUE THREAD

**Issue by kjgarza** [datacite/akita#166] opened 2021-06-25 12:49 UTC
### Expected Behaviour

Facets when unchecked should return to their previous state.

### Current Behaviour

When unchecking a facet from a multiple field( Co-authors, FoS) the facet counts and order gets mixed and doesn't return to their previous state. 

![image](https://user-images.githubusercontent.com/1092861/123427065-71885b00-d5c4-11eb-9edd-4b4f7a6aae8d.png)

https://commons.datacite.org/orcid.org/0000-0003-1419-2405?orcid=0000-0003-1419-2405&field-of-science=media_and_communications

### Steps to Reproduce

1. Select an item from the FoS facet by checking the Box
2. Remove the check box
3. see quantifies and number do not return to previous state

### Hypothesis

State gets lost after unchecking the checkbox

**Comment by richardhallett** [comment] 2021-07-26 19:41
Unable to reproduce. Potentially fixed with other refactoring as part of #154

**Closed by richardhallett** 2021-07-26 19:41 UTC
Labels: bug
